### ISSUE TITLE
Options being cut off 

### ISSUE THREAD

**Issue by skye-g** [VinnyDyn/NNTags#5]
Hi - this looks awesome, but I'm having an issue where the options aren't wrapping under the filter bar, and the filter bar is taking up most of the screen.  Is there a way to resolve this?

Thanks!

![2020-10-NNScreenshot](https://user-images.githubusercontent.com/72484949/95288643-5c419400-08b0-11eb-9485-594a890369dd.png)

**Comment by VinnyBasile** [comment]
Hello @skye-g ! Thank you for the feedback! I will check this problem, please wait until the next week!

**Comment by fneiderud** [comment]
Would be great if you could fix! We are seeing the same behaviour...
Worked great a few months ago, but all of a sudden it stopped working. MS update?

**Comment by VinnyBasile** [comment]
@fneiderud and @skye-g , sorry for the delay :)
Please download the new release [VinnyBComponents 2.0.1.1](https://github.com/VinnyDyn/StatusReasonKanban/releases/tag/2.0.1.1)

I will wait your confirmation to close this issue

**Comment by froxybox** [comment]
It's working for me!
Thanks so much, @VinnyDyn ⭐

**Comment by skye-g** [comment]
Edit: I was wrong - forgot to update the number of rows. 😳
Looks like it's working!  Thank you, @VinnyDyn!

**Comment by VinnyBasile** [comment]
I'll change a parameter to set by default 250 records and add paging.

**Comment by fneiderud** [comment]
Works fine now, thanks alot @VinnyDyn!

**Comment by skye-g** [comment]
Thanks for this! I finally reset my password for this account!
